--- ### Spring 配置
spring:
  application:
    name: continew-admin-schedule-server
  ## 环境配置
  profiles:
    # 启用的环境（通过 Maven Profile 指定，默认 dev）
    active: @profiles.active@

--- ### 日志配置
logging:
  config: classpath:logback-spring.xml